export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';


export const GET_OWNER_RESTAURANT = 'GET_OWNER_RESTAURANT';
export const SAVE_OWNER_RESTAURANT = 'SAVE_OWNER_RESTAURANT';
export const GET_OWNER_MENU_ITEMS = 'GET_OWNER_MENU_ITEMS';
export const GET_OWNER_ORDERS = 'GET_OWNER_ORDERS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANT_BY_ID = 'GET_RESTAURANT_BY_ID';
export const GET_MENU_ITEMS_BY_RESTAURANT = 'GET_MENU_ITEMS_BY_RESTAURANT';

export const GET_ALL_ORDERS =  'GET_ALL_ORDERS';
export const GET_USER_ORDERS = 'GET_USER_ORDERS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';